/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const before_Purchases_Create_Update = require('./code/before-purchases-create-update');
const before_Redemptions_Create = require('./code/before-redemptions-create');

class customer_loyaltySrv extends LCAPApplicationService {
    async init() {

        this.before(['CREATE', 'UPDATE'], 'Purchases', async (request) => {
            await before_Purchases_Create_Update(request);
        });

        this.before('CREATE', 'Redemptions', async (request) => {
            await before_Redemptions_Create(request);
        });

        return super.init();
    }
}


module.exports = {
    customer_loyaltySrv
};